"""adicionar itens novo pedido

Revision ID: b15f62b7ff3b
Revises: 9c3a530c9c17
Create Date: 2026-05-29 04:37:49.439263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15f62b7ff3b'
down_revision = '9c3a530c9c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
